//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostLowApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ssn { get; set; }
        public int departmentId { get; set; }
        public Nullable<int> storeNumber { get; set; }
        public Nullable<long> phoneNumber { get; set; }
        public Nullable<decimal> sallary { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    
        public virtual department department { get; set; }
    }
}
