//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostLowApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class visit
    {
        [Display(Name = "Customer ID")]
        public int customerId { get; set; }

        [Display(Name = "Store Number")]
        public int storeNumber { get; set; }

        [Display(Name = "Date")]
        public System.DateTime date { get; set; }

        [Display(Name = "Amount Spent")]
        public Nullable<decimal> amountSpent { get; set; }
    
        public virtual member member { get; set; }
        public virtual store store { get; set; }
    }
}
